### ISSUE TITLE
Logging 404 errors displays port as undefined

### ISSUE THREAD

**Issue by rdominy** [jhuckaby/pixl-server-web#1]
This is a minor issue, but if a URL is invoked without a port and pixl-server-web logs a 404, it displays "undefined" in the port.  Example:

"url":"https://torque.admission.net:undefined/mraid.js"

**Comment by jhuckaby** [comment]
Ah, thank you.  Looks like this only happens if the URL was upstream-HTTPS, as in served via an ELB, then handled as HTTP in pixl-server-web, but the code that reconstructs the URL for logging detects that SSL was active (via header sniff), so it tries to add the HTTPS port, which is undefined in this case, because pixl-server-web isn't actually serving HTTPS.  Will be fixed in next release, thanks!
